### ISSUE TITLE
Apache version tries to link sites-available to sites-available

### ISSUE THREAD

**Issue by smmccabe** [AcroMedia/ansible-role-letsencrypt#2]
It should actually try and link sites-available to sites-enabled, but it just uses the same variable for both src and destination.

**Comment by dale-c-anderson** [comment]
Fixed by https://github.com/AcroMedia/ansible-role-letsencrypt/pull/3/commits/3cc4dfb3770d64ca57dc3c5dde3b53bb005db61f
